DROP TABLE IF EXISTS employees;
DROP TABLE IF EXISTS  departments;
DROP TABLE IF EXISTS roles;

CREATE TABLE employees (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(30) NOT NULL,
  last_name VARCHAR(30) NOT NULL,
CONSTRAINT fk_roles
FOREIGN KEY (roles_id)
REFERENCES roles(id)
ON DELETE SET NULL,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE department (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  department VARCHAR(30) NOT NULL
);

CREATE TABLE role (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  department VARCHAR(30) NOT NULL,
  responsibility TEXT NOT NULL
);
